// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewSite_WebAPI.Data;

#nullable disable

namespace ReviewSite_WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221227001016_SeedProductsTable")]
    partial class SeedProductsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReviewSite_WebAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 12, 26, 17, 10, 16, 763, DateTimeKind.Local).AddTicks(9767),
                            Description = "Lorem ipsum dolor sit amet.",
                            ImageUrl = "./Images/white_t-shirt.jpg",
                            Name = "White T-Shirt",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 12, 26, 17, 10, 16, 763, DateTimeKind.Local).AddTicks(9795),
                            Description = "Lorem ipsum dolor sit amet.",
                            ImageUrl = "./Images/black_t-shirt.jpg",
                            Name = "Black T-Shirt",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 12, 26, 17, 10, 16, 763, DateTimeKind.Local).AddTicks(9798),
                            Description = "Lorem ipsum dolor sit amet.",
                            ImageUrl = "./Images/red_t-shirt.jpg",
                            Name = "Red T-Shirt",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 12, 26, 17, 10, 16, 763, DateTimeKind.Local).AddTicks(9799),
                            Description = "Lorem ipsum dolor sit amet.",
                            ImageUrl = "./Images/blue_t-shirt.jpg",
                            Name = "Blue T-Shirt",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 12, 26, 17, 10, 16, 763, DateTimeKind.Local).AddTicks(9801),
                            Description = "Lorem ipsum dolor sit amet.",
                            ImageUrl = "./Images/maroon_t-shirt.jpg",
                            Name = "Maroon T-Shirt",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 12, 26, 17, 10, 16, 763, DateTimeKind.Local).AddTicks(9803),
                            Description = "Lorem ipsum dolor sit amet.",
                            ImageUrl = "./Images/yellow_t-shirt.jpg",
                            Name = "Yellow T-Shirt",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
